"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowRight, Calculator, CaretDown, Check, FilePdf, Heart, Minus, Package, Plus, SealCheck, ShoppingCartSimple, Storefront, Truck } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { CatalogProductCard } from "../../components/catalog-product-card";
import { SiteChrome } from "../../components/site-chrome";
import { catalogProducts, CatalogProduct } from "../../catalog/data";
import { readCart, readFavorites, writeCart, writeFavorites } from "../../lib/commerce";

export default function ProductPage(){
 const {slug}=useParams<{slug:string}>(); const router=useRouter(); const product=catalogProducts.find(item=>item.slug===slug);
 const [quantity,setQuantity]=useState(1); const [favorite,setFavorite]=useState(false); const [added,setAdded]=useState(false); const [calcOpen,setCalcOpen]=useState(false); const [area,setArea]=useState(12); const [reserve,setReserve]=useState(10); const [view,setView]=useState(0); const [tab,setTab]=useState<"description"|"specs">("description"); const [relatedAdded,setRelatedAdded]=useState<string[]>([]); const [relatedFavorites,setRelatedFavorites]=useState<string[]>([]);
 useEffect(()=>{if(product){const ids=readFavorites();setFavorite(ids.includes(product.id));setRelatedFavorites(ids);}},[product]);
 const calculated=useMemo(()=>Math.max(1,Math.ceil(area*(1+reserve/100)/(product?.category==="Гипсокартон"?3:2.98))),[area,product,reserve]);
 if(!product)return <SiteChrome><div className="not-found-card"><h1>Товар не найден</h1><Link className="primary-inline" href="/catalog">Вернуться в каталог<ArrowRight/></Link></div></SiteChrome>;
 function toggle(){const ids=readFavorites();const next=ids.includes(product!.id)?ids.filter(id=>id!==product!.id):[...ids,product!.id];writeFavorites(next);setFavorite(next.includes(product!.id));}
 function add(item:CatalogProduct=product!,count=quantity){const current=readCart();const id=`product-${item.id}`;writeCart([...current.filter(entry=>entry.id!==id),{id,title:item.name,price:item.price,quantity:count,image:item.image,detail:`${item.brand} · ${item.unit}`}]);if(item.id===product!.id)setAdded(true);else setRelatedAdded(v=>[...v,item.id]);}
 const variants=catalogProducts.filter(item=>item.category===product.category);
 const related=catalogProducts.filter(item=>item.id!==product.id&&item.category===product.category).slice(0,3);
 return <SiteChrome><div className="inner-canvas product-page">
  <nav className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><Link href="/catalog">Каталог</Link><span>/</span><Link href={`/catalog?category=${product.category==="Гипсокартон"?"drywall":"sheet"}#products`}>{product.category}</Link><span>/</span><span>{product.name}</span></nav>
  <section className="product-detail-layout"><div className="product-gallery-wrap"><div className="product-thumbnails">{["Общий вид","Материал","Упаковка"].map((label,index)=><button aria-label={label} className={view===index?"is-active":""} key={label} onClick={()=>setView(index)} type="button"><Image alt="" fill sizes="80px" src={product.image}/></button>)}</div><div className={`product-gallery view-${view}`}><span className="product-gallery-badge">Хит продаж</span><Image alt={product.name} fill priority sizes="(max-width:767px) 100vw, 50vw" src={product.image}/><small>Фото товара может незначительно отличаться от партии</small></div></div>
  <div className="product-info"><div className="product-brand-row"><p className="card-eyebrow">{product.brand}</p><span>Код: {product.code}</span></div><h1>{product.name}</h1><div className="product-rating"><b>4,9</b><span>★★★★★</span><a href="#reviews">12 отзывов</a></div><div className="product-stock-large"><span/><b>В наличии: {product.stock.toLocaleString("ru-RU")} {product.unit}</b><small>Остаток по МоемуСкладу на 04.09.2026</small></div>
  {variants.length>1&&<div className="product-variants"><b>{product.category==="Гипсокартон"?"Толщина и исполнение":"Варианты товара"}</b><div>{variants.map(item=><Link className={item.id===product.id?"is-active":""} href={`/product/${item.slug}`} key={item.id}>{item.name.includes("влагостойкий")?"Влагостойкий ":"Стандарт "}{item.specs?.find(([name])=>name==="Толщина")?.[1]||""}</Link>)}</div></div>}
  <div className="product-price-large"><strong>{product.price.toLocaleString("ru-RU")} ₽</strong>{product.oldPrice&&<del>{product.oldPrice} ₽</del>}<small>/ {product.unit}</small></div><div className="product-buy-row"><div className="cart-quantity"><button aria-label="Уменьшить" onClick={()=>setQuantity(Math.max(1,quantity-1))} type="button"><Minus/></button><b>{quantity}</b><button aria-label="Увеличить" onClick={()=>setQuantity(quantity+1)} type="button"><Plus/></button></div><button className="primary-inline" onClick={()=>add()} type="button">{added?<>В корзине<Check/></>:<>В корзину<ShoppingCartSimple/></>}</button><button aria-label="В избранное" className={`product-favorite-large ${favorite?"is-active":""}`} onClick={toggle} type="button"><Heart weight={favorite?"fill":"regular"}/></button></div>{added&&<button className="go-cart" onClick={()=>router.push("/cart")} type="button">Перейти в корзину<ArrowRight/></button>}
  <button className={`quantity-calc-toggle ${calcOpen?"is-open":""}`} onClick={()=>setCalcOpen(!calcOpen)} type="button"><Calculator weight="bold"/><span><b>Рассчитать количество</b><small>По площади помещения с запасом</small></span><CaretDown/></button>{calcOpen&&<div className="quantity-calculator"><label>Площадь, м²<input min="1" onChange={e=>setArea(Number(e.target.value))} type="number" value={area}/></label><label>Запас<select onChange={e=>setReserve(Number(e.target.value))} value={reserve}><option value="5">5%</option><option value="10">10%</option><option value="15">15%</option></select></label><div><small>Понадобится</small><strong>{calculated} {product.unit}</strong><button onClick={()=>{setQuantity(calculated);setCalcOpen(false);}} type="button">Применить</button></div></div>}
  <div className="product-service-notes"><article><Truck/><span><b>Доставка на объект</b><small>Рассчитаем по адресу</small></span></article><article><Storefront/><span><b>Самовывоз сегодня</b><small>Ростовское шоссе, 24А</small></span></article></div></div></section>
  <section className="product-content"><div className="product-tabs"><button className={tab==="description"?"is-active":""} onClick={()=>setTab("description")} type="button">Описание</button><button className={tab==="specs"?"is-active":""} onClick={()=>setTab("specs")} type="button">Характеристики</button></div>{tab==="description"?<div className="product-description"><div><p className="eyebrow">О товаре</p><h2>Для каких работ подходит</h2><p>{product.description}</p><ul><li><Check/>Проверяем количество и внешний вид перед отгрузкой</li><li><Check/>Подберём совместимые профиль, крепёж и смеси</li><li><Check/>Можно включить в готовый комплект материалов</li></ul></div><aside><Package/><b>Комплектуем под задачу</b><p>Подберём совместимые материалы и проверим наличие перед оплатой.</p><Link href="/business/assembly">Помочь с комплектом<ArrowRight/></Link></aside></div>:<div className="product-specs"><div><p className="eyebrow">Характеристики</p><h2>Основные параметры</h2></div><dl>{product.specs?.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}<div><dt>Бренд</dt><dd>{product.brand}</dd></div><div><dt>Единица продажи</dt><dd>{product.unit}</dd></div></dl></div>}</section>
  <section className="product-receiving"><div><p className="eyebrow">Получение товара</p><h2>Выберите удобный способ</h2></div><div className="receiving-grid"><article><span><Truck weight="bold"/></span><h3>Доставка на объект</h3><p>Подберём машину по объёму заказа и согласуем интервал.</p><Link href="/delivery">Условия доставки<ArrowRight/></Link></article><article><span><Storefront weight="bold"/></span><h3>Самовывоз со склада</h3><p>Подготовим заказ к приезду и проверим комплектность.</p><Link href="/contacts">Как нас найти<ArrowRight/></Link></article><article><span><SealCheck weight="bold"/></span><h3>Проверка заказа</h3><p>Менеджер подтвердит остатки и замены до оплаты.</p><Link href="/business/assembly">Комплектация<ArrowRight/></Link></article></div></section>
  <section className="product-documents"><div><p className="eyebrow">Документы</p><h2>Файлы по товару</h2><p>Паспорта и сертификаты запрашиваются по актуальной партии.</p></div><div><article><FilePdf weight="duotone"/><span><b>Сертификат соответствия</b><small>PDF · предоставим по запросу</small></span><button type="button">Запросить</button></article><article><FilePdf weight="duotone"/><span><b>Паспорт качества</b><small>PDF · для текущей партии</small></span><button type="button">Запросить</button></article></div></section>
  <section className="related-products"><div className="section-heading-row"><div><p className="eyebrow">Похожие позиции</p><h2>Сравните варианты</h2></div><Link href={`/catalog?category=${product.category==="Гипсокартон"?"drywall":"sheet"}#products`}>Смотреть категорию<ArrowRight/></Link></div><div className="catalog-product-grid">{related.map(item=><CatalogProductCard added={relatedAdded.includes(item.id)} favorite={relatedFavorites.includes(item.id)} key={item.id} onAdd={()=>add(item,1)} onFavorite={()=>{const next=relatedFavorites.includes(item.id)?relatedFavorites.filter(id=>id!==item.id):[...relatedFavorites,item.id];setRelatedFavorites(next);writeFavorites(next);}} product={item}/>)}</div></section>
 </div></SiteChrome>;
}
