import Link from "next/link";
import { Clock, Envelope, MapPin, Phone } from "@phosphor-icons/react/dist/ssr";
import { LeadForm } from "../components/lead-form";
import { SiteChrome } from "../components/site-chrome";

export default function ContactsPage() {
  return <SiteChrome><div className="inner-canvas service-page contacts-page"><nav aria-label="Хлебные крошки" className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><span>Контакты</span></nav><section className="service-hero"><div><p className="eyebrow">Строяков · Краснодар</p><h1>Контакты</h1><p>Поможем с заказом, доставкой и получением. Чтобы ответить быстрее, подготовьте номер заказа или коротко опишите задачу.</p></div><div className="service-hero-aside"><p className="eyebrow">Что указать в обращении</p><ul><li>Номер заказа или корзины</li><li>Адрес объекта</li><li>Коротко суть вопроса</li></ul></div></section>
    <section className="service-section"><div className="service-section-heading"><div><p className="eyebrow">Связь без переадресаций</p><h2>Куда обратиться</h2></div><p>Для телефона и мессенджера разные задачи — так обращение быстрее попадёт нужному человеку.</p></div><div className="contact-grid"><a href="tel:+79280446070"><Phone weight="bold"/><span>Заказы и доставка<strong>+7 928 044-60-70</strong><small>Оформление, статус заказа и условия доставки</small></span></a><a href="tel:+79183410144"><Phone weight="bold"/><span>Магазин и склад<strong>+7 918-341-01-44</strong><small>Наличие, самовывоз и вопросы по точке продаж</small></span></a><a href="mailto:info@stroyakov.ru"><Envelope weight="bold"/><span>Электронная почта<strong>info@stroyakov.ru</strong><small>Сметы, документы и реквизиты</small></span></a></div></section>
    <section className="location-section"><div className="location-card"><span><MapPin weight="fill"/></span><p className="eyebrow">Магазин и склад</p><h2>Приехать в Строяков</h2><strong>Краснодар<br/>Ростовское шоссе, 24 лит. А</strong><p>Перед самовывозом дождитесь подтверждения комплектации от менеджера.</p><a className="primary-inline" href="https://yandex.ru/maps/?text=Краснодар%2C%20Ростовское%20шоссе%2C%2024%20лит.%20А" rel="noreferrer" target="_blank">Построить маршрут<MapPin weight="bold"/></a></div><div className="working-hours"><Clock weight="bold"/><div><p className="eyebrow">Режим работы</p><h3>Уточните время визита</h3><p>Менеджер подтвердит, когда заказ будет готов к выдаче.</p><a href="tel:+79183410144">Позвонить на склад</a></div></div></section>
    <section className="service-section contact-form-section"><div><p className="eyebrow">Обратная связь</p><h2>Опишите вопрос</h2><p>Если удобно не звонить, оставьте номер и короткий контекст. По вопросу заказа укажите его номер.</p></div><LeadForm button="Отправить вопрос" title="Мы ответим по задаче"/></section>
  </div></SiteChrome>;
}
