import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle, ClipboardText, Package, Ruler, Truck } from "@phosphor-icons/react/dist/ssr";
import { SiteChrome } from "../components/site-chrome";
import { LeadForm } from "../components/lead-form";

export default function BusinessPage() {
  const services = [[ClipboardText, "Комплектация по смете", "Проверим наименования, количества и предложим аналоги."], [Ruler, "Подбор аналогов", "Сохраним характеристики системы и бюджет."], [Package, "Поставка по этапам", "Разделим заказ по графику работ и подготовим к выдаче."], [Truck, "Доставка на объект", "Подберём транспорт, маршрут и разгрузку."] ] as const;
  return <SiteChrome><div className="inner-canvas service-page"><nav aria-label="Хлебные крошки" className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><span>Для бизнеса</span></nav><section className="service-hero"><div><p className="eyebrow">Комплектация объектов</p><h1>Снабжение объектов<br />без хаоса</h1><p>Комплектуем по смете, подбираем аналоги и согласуем поставки по этапам работ. Один контакт по заявке — от расчёта до документов.</p><div className="hero-inline-actions"><Link className="primary-inline" href="/business/assembly">Отправить смету<ArrowRight /></Link><a href="tel:+79280446070">+7 928 044-60-70</a></div></div><div className="service-hero-aside"><p className="eyebrow">Что берём на себя</p><ul><li>Разбор сметы и состава заявки</li><li>Проверка наличия и аналогов</li><li>План отгрузок по этапам</li><li>Закрывающие документы</li></ul></div></section>
    <section className="service-section"><div className="service-section-heading"><div><p className="eyebrow">Формат работы</p><h2>Подключаемся там, где сложно</h2></div><p>От одной сметы до регулярного снабжения объекта — объём работы согласуем заранее.</p></div><div className="business-service-grid">{services.map(([Icon, title, text], index) => <article key={title}><div><span><Icon weight="bold" /></span><p className="card-eyebrow">0{index + 1}</p><h3>{title}</h3><p>{text}</p></div><Image alt="" height={160} src={`/assets/services/${["calculation", "products", "order", "delivery"][index]}.png`} width={210}/></article>)}</div></section>
    <section className="business-process"><div><p className="eyebrow">Порядок без лишних созвонов</p><h2>Как строится работа</h2></div><ol>{[["Получили заявку", "Смета, список или корзина"], ["Проверили", "Наличие и подходящие аналоги"], ["Согласовали", "Состав, стоимость и сроки"], ["Отгрузили", "Документы и один ответственный"]].map(([title, text], index) => <li key={title}><span>0{index + 1}</span><b>{title}</b><small>{text}</small></li>)}</ol></section>
    <section className="service-section business-form-section"><div><p className="eyebrow">Начнём с одного объекта</p><h2>Пришлите смету — вернёмся с планом</h2><p>Подойдёт таблица, PDF, список или корзина. Неоднозначные позиции вынесем на уточнение.</p><ul><li><CheckCircle weight="fill"/>Согласованный состав</li><li><CheckCircle weight="fill"/>План поставок</li><li><CheckCircle weight="fill"/>Условия по каждой заявке</li></ul></div><LeadForm button="Отправить заявку" title="Контакт по заявке"/></section>
  </div></SiteChrome>;
}
