import Image from "next/image";
import Link from "next/link";
import { Bank, CheckCircle, Clock, MapPin, Storefront, Truck, Wallet } from "@phosphor-icons/react/dist/ssr";
import { SiteChrome } from "../components/site-chrome";
import { LeadForm } from "../components/lead-form";

export default function DeliveryPage() {
  return <SiteChrome><div className="inner-canvas service-page"><nav aria-label="Хлебные крошки" className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><span>Доставка и оплата</span></nav><section className="service-hero"><div><p className="eyebrow">Сервис Строяков</p><h1>Доставка<br />и оплата</h1><p>Привезём материалы на объект или подготовим к самовывозу. Стоимость и ближайшее окно подтвердим после проверки адреса и состава заказа.</p></div><div className="service-hero-aside"><p className="eyebrow">Быстрее посчитаем, если есть</p><ul><li>Номер заказа или корзина</li><li>Адрес и условия подъезда</li><li>Нужна ли разгрузка</li></ul><a href="tel:+79280446070">+7 928 044-60-70</a></div></section>
    <section className="service-section"><div className="service-section-heading"><div><p className="eyebrow">Получение заказа</p><h2>Как получить материалы</h2></div><p>Работаем по Краснодару, краю и ЮФО. Сложные маршруты и разгрузку согласовываем отдельно.</p></div><div className="delivery-methods"><article><span><Truck weight="bold" /></span><div><h3>Доставка по Краснодару</h3><p>Подберём транспорт под объём и ограничения объекта.</p></div><Image alt="Доставка строительных материалов на объект" height={150} src="/assets/services/delivery.png" width={210}/></article><article><span><MapPin weight="bold" /></span><div><h3>Краевой и межгород</h3><p>Рассчитаем маршрут и согласуем дату после проверки заявки.</p></div></article><article><span><Storefront weight="bold" /></span><div><h3>Самовывоз со склада</h3><p>Краснодар, Ростовское шоссе, 24 лит. А. Заказ подготовим заранее.</p></div></article></div></section>
    <section className="service-section rate-section"><div><div className="service-section-heading vertical"><div><p className="eyebrow">Расчёт стоимости</p><h2>Назовём цену после проверки адреса</h2></div><p>Расстояние — только часть расчёта. Учитываем состав заказа, вес, тип машины и условия подъезда к объекту.</p></div><LeadForm button="Рассчитать доставку" compact title="Адрес объекта"/></div><div className="delivery-conditions"><article><Clock /><h3>Окно доставки</h3><p>Подтверждаем дату и интервал после комплектации заказа.</p></article><article><Truck /><h3>Разгрузка</h3><p>Манипулятор, боковая или ручная разгрузка — по условиям объекта.</p></article><article><CheckCircle /><h3>Приёмка</h3><p>Проверяйте количество и внешний вид материалов при получении.</p></article></div></section>
    <section className="service-section"><div className="service-section-heading"><div><p className="eyebrow">Способы расчёта</p><h2>Оплата как удобно</h2></div><p>Для юридических лиц подготовим счёт и комплект закрывающих документов.</p></div><div className="payment-methods"><article><Wallet /><h3>Банковской картой</h3><p>После подтверждения наличия и состава заказа.</p></article><article><Bank /><h3>По счёту</h3><p>Безналичная оплата для компаний и ИП.</p></article><article><Storefront /><h3>При получении</h3><p>Доступность способа подтвердит менеджер.</p></article></div></section>
    <section className="service-section faq-section"><div><p className="eyebrow">Перед оформлением</p><h2>Важно знать</h2></div><div>{["Как рассчитывается стоимость доставки?", "Когда станет известна точная дата?", "Можно ли заказать разгрузку?", "Что проверить при получении?"].map((question, index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{index === 0 ? "После проверки адреса, веса, габаритов, типа транспорта и условий подъезда. Предварительную сумму сообщит менеджер." : "Менеджер уточнит условия при подтверждении заказа и зафиксирует их в заявке."}</p></details>)}</div></section>
  </div></SiteChrome>;
}
