import Link from "next/link";
import { CheckCircle, ClipboardText, Package, Ruler, Truck } from "@phosphor-icons/react/dist/ssr";
import { LeadForm } from "../../components/lead-form";
import { SiteChrome } from "../../components/site-chrome";

export default function AssemblyPage() {
  return <SiteChrome><div className="inner-canvas service-page"><nav aria-label="Хлебные крошки" className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><Link href="/business">Для бизнеса</Link><span>/</span><span>Комплектация</span></nav><section className="service-hero"><div><p className="eyebrow">Услуга для бизнеса</p><h1>Комплектация объекта<br />по смете</h1><p>Проверим позиции по фактическому ассортименту, предложим согласованные аналоги и соберём поставку под этапы работ.</p></div><div className="service-hero-aside"><p className="eyebrow">Нужен управляемый процесс</p><ul><li>Один ответственный менеджер</li><li>Замены только после согласования</li><li>Проверка остатка до счёта</li><li>Поставка по этапам</li></ul></div></section>
    <section className="service-section"><div className="service-section-heading"><div><p className="eyebrow">Состав услуги</p><h2>Что входит в комплектацию</h2></div><p>Каждый этап согласуем отдельно: замены не попадут в заявку без подтверждения.</p></div><div className="assembly-grid">{[[ClipboardText, "Разбор сметы", "Проверим наименования, характеристики и количества."], [Ruler, "Подбор аналогов", "Предложим варианты из фактического ассортимента."], [Package, "План отгрузок", "Разделим заказ под этапы работ."], [Truck, "Доставка или самовывоз", "Подтвердим маршрут, стоимость и ближайшее окно."]].map(([Icon, title, text]) => <article key={String(title)}><span><Icon weight="bold" /></span><div><h3>{String(title)}</h3><p>{String(text)}</p></div></article>)}</div></section>
    <section className="business-process"><div><p className="eyebrow">Как идёт работа</p><h2>Понятно на каждом этапе</h2></div><ol>{[["Получили смету", "Файл, список или корзина"], ["Разобрали позиции", "Проверили характеристики"], ["Согласовали замены", "Только с подтверждением"], ["Подготовили отгрузку", "По этапу и адресу"]].map(([title, text], index) => <li key={title}><span>0{index + 1}</span><b>{title}</b><small>{text}</small></li>)}</ol></section>
    <section className="service-section business-form-section"><div><p className="eyebrow">Следующий шаг</p><h2>На выходе — согласованный комплект</h2><p>В ответе укажем состав, аналоги, наличие, стоимость и условия отгрузки.</p><ul><li><CheckCircle weight="fill"/>Согласованный список</li><li><CheckCircle weight="fill"/>Отмеченные замены</li><li><CheckCircle weight="fill"/>План поставки</li></ul></div><LeadForm button="Отправить смету" title="Пришлите смету на проверку"/></section>
  </div></SiteChrome>;
}
